name: 🚀 Deploy website on push
on:
  push:
    branches: [ prod ]
jobs:
  web-deploy:
    environment: production
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.typanic.sanzmoses.net
        username: u141166830.typanic
        password: ${{ secrets.ftp_password }}